---
title: "Question 3"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(forecast)
```


# 1. Load the data and plot Google trend and EV fraction trend
```{r}
df <- read.csv("UK_pivotGoogle.csv")
colnames(df)[1] <- "Year"
df$Year <- as.character(df$Year)

# create function to normalize data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}


#df <- df %>% mutate_if(is.numeric, normalize)

plot(df$Year, df$Total)
plot(df$Year, df$EV_Fraction)
```


###### The goal of this is to show that as Google Trends increases so does EV Fraction. The data set only has up to 2019 cause in 2020 google trends wasn't as high (feel free to change).


# 2. Check correlation Ev_Fraction ~ Google Trend

```{r}
# Total predicts EV_Fraction
m1 <- lm(EV_Fraction ~ Total -1, df)
m1$coefficients

```


```{r}
# Seem very correlated
cor(df[-1])
```

# 3. Forecast and then plot forecast

```{r}
# type of forecast is not good so try other type
a1 <- forecast(df$Total, 11)


# DF for results
future <- NULL
future$Year <- c(2020:2030)
future <- data.frame(future)
future$Total_Forecast <- a1$upper[,2]

future$coef <- m1$coefficients
future <- future %>%
  mutate(Future_EV_fraction = Total_Forecast * coef)

# Plot the future
plot(future$Year, future$Total_Forecast)
plot(future$Year, future$Future_EV_fraction)
```


# 4. This is what you put into excel
```{r}
print(future$Future_EV_fraction)
```

